server:
  port: 8888
  tomcat:
    accesslog:
      directory: logs/tomcat/
      enabled: true
    connection-timeout: 1s
    max-connections: 1000
spring:
  application:
    name: demo-dev
  config:
    activate:
      on-profile: test  #2.4以后使用
  profiles:
    include: custom-dev
# 自定义配置
custom-config:
  user-name: chen
  userAge: 30