server:
  port: ${random.int(8080,8999)}
  tomcat:
    accesslog:
      directory: logs/tomcat/
      enabled: true
    connection-timeout: 1s
    max-connections: 1000
spring:
  application:
    name: demo-dev
  config:
    activate:
      on-profile: dev  #2.4以后使用
    #  config:
    #    activate:
    #      on-profile: dev
# 自定义配置
custom-config:
  user-name: chen
  user-age: 30